### ISSUE TITLE
Gooseberry Jam recipe consumes glass bottles?

### ISSUE THREAD

**Issue by COLDW0LF** [davidjjung/copperpot#3]
Love the mod... it's a wonderful and unique idea for an enhancement to Farmer's Delight!
I'm really excited to see what else you're cooking up (pardon the horrendous pun).

I noticed that the gooseberry jam recipe is giving back 1 glass bottle when it finishes cooking...
the only problem is, it uses 3 (1x honey, 2x gooseberry juice) bottles in the recipe!
I don't know if that's something you can solve on your end, but I noticed that maple bacon fudge drops 2 bottles.

Thanks again!

**Comment by davidjjung** [comment]
Thank you for the nice words, haha. I'm pretty sure it's on Bayou Blues's end. They don't have a container listed for gooseberry juice, which would explain only the honey bottle's container (ie the single bottle) to drop when cooking. I'll submit a github issue there--thanks for your patience!

**Comment by COLDW0LF** [comment]
I suspected it might be something on their end... my pleasure, I'll keep an eye out for other inconsistencies and let you know! :)

**Comment by davidjjung** [comment]
Update--unfortunately, due to the way gooseberry jam is shapelessly crafted, it appears the issue cannot be fixed. This is because the shapeless recipe (three GB juice, one honey) crafts three jam bottles, which means the GB juice can't leave its bottles behind in the crafting grid (since the crafted result is also a bottled item). Vanilla json recipes don't currently have a way to make a recipe conditionally use their entire containers as well, which is where the problem lies. I'll change the recipe to use actual gooseberries instead--I also realize the current setup is actually less efficient than the crafting recipe, so I'll balance that as well. Cheers!

**Comment by COLDW0LF** [comment]
Nice one, thanks for your hard work!
