### ISSUE TITLE
extension moment

### ISSUE THREAD

**Issue by thelegitdolt** [davidjjung/copperpot#9]
drinking adzuki paste/any food item with an additive effect while you have extension causes the effects timers to snowball quite fast lol
honestly this sounds like more an autumnity issue then one from here, since this also works with beserking from neapolitan

**Comment by davidjjung** [comment]
yeagh,, upon further review, i'd rather put this on Autumnity's plate for now, since the concept of theoretically unlimited effect extension is so dicey (with food that extends effects it's inherently limited by hunger, whereas with potions it's limited by only the discretion of the extension effect itself). that said, adzuki paste/maple bacon fudge will probably be eliminated moving forward, so hopefully that's a step in a more balanced direction 👍
